name: Build

on: 
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
  REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
  REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
  REACT_APP_MESSENGER_ID: ${{ secrets.REACT_APP_MESSENGER_ID }}
  REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID}}
  REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}

jobs:
  build-and-deploy-preview:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v3

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v3

      - name: 🔧 Install
        run: npm install

      - name: 🏗️ Build
        run: npm run build

      - name: 🚀 Deploy Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          baseurl: "https://trandrew1023.github.io/edi-translator/${{ github.event.pull_request.number }}"
          commit_message: Deploy preview for pull request ${{ github.event.pull_request.number }}
      
      - name: Post preview comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `
              Preview of this branch has been deployed.

              To view the preview, visit https://trandrew1023.github.io/edi-translator/${{ github.event.pull_request.number }}
            `;
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

  cleanup-preview:
    needs: [build-and-deploy-preview]
    if: github.event.pull_request.merged == true || github.event.pull_request.closed == true
    runs-on: ubuntu-latest
    steps:
      - name: ❌ Cleanup Preview
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const branchName = 'pull-request-preview-' + context.payload.pull_request.number;
            github.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `heads/${branchName}`
            });

      - name: Post closing comment
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `
              Preview of this branch has been deleted.

              The preview URL is no longer accessible.
            `;
            github.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });